var queryData = [
  {'type': '午A', 'location': "E'", 'area': '90', 'building': 'E1', unit: 1, 'room': 101, description: '两室一厅一卫'},
  {'type': '午A', 'location': "E'", 'area': '90', 'building': 'E1', unit: 1, 'room': 201, description: '两室一厅一卫'},
  {'type': '午A', 'location': "E'", 'area': '90', 'building': 'E1', unit: 1, 'room': 301, description: '两室一厅一卫'},
  {'type': '午A', 'location': "E'", 'area': '90', 'building': 'E1', unit: 1, 'room': 401, description: '两室一厅一卫'},
  {'type': '午A', 'location': "E'", 'area': '90', 'building': 'E2', unit: 4, 'room': 101, description: '两室一厅一卫'},
  {'type': '午A', 'location': "E'", 'area': '90', 'building': 'E2', unit: 1, 'room': 201, description: '两室一厅一卫'},
  {'type': '午A', 'location': "E'", 'area': '90', 'building': 'E2', unit: 1, 'room': 301, description: '两室一厅一卫'},
  {'type': '午A', 'location': "E'", 'area': '90', 'building': 'E2', unit: 2, 'room': 401, description: '两室一厅一卫'},
  {'type': '午A', 'location': "E'", 'area': '90', 'building': 'E3', unit: 1, 'room': 101, description: '两室一厅一卫'},
  {'type': '午A', 'location': "E'", 'area': '90', 'building': 'E3', unit: 3, 'room': 201, description: '两室一厅一卫'},
  {'type': '午A', 'location': "E'", 'area': '90', 'building': 'E3', unit: 1, 'room': 301, description: '两室一厅一卫'},
  {'type': '午A', 'location': "E'", 'area': '90', 'building': 'E3', unit: 1, 'room': 401, description: '两室一厅一卫'},
  {'type': '辰A', 'location': "E''", 'area': '120', 'building': 'E18', unit: 2, 'room': 101, description: '两室两厅一卫'},
  {'type': '辰A', 'location': "E''", 'area': '120', 'building': 'E18', unit: 2, 'room': 201, description: '两室两厅一卫'},
  {'type': '辰A', 'location': "E''", 'area': '120', 'building': 'E19', unit: 1, 'room': 301, description: '两室两厅一卫'},
  {'type': '辰A', 'location': "E''", 'area': '120', 'building': 'E19', unit: 4, 'room': 401, description: '两室两厅一卫'},
  {'type': '辰A', 'location': "E''", 'area': '120', 'building': 'E19', unit: 3, 'room': 101, description: '两室两厅一卫'},
];
